#!/usr/bin/env node
'use strict';

// Regenerates src/types.js from doc/wots_incident_types_raw.json.
// Run: node scripts/build-types.js
//
// Emits the slim per-type shape the submit path needs:
//   { typeName, group, subgroup, snoozable, redirect911, redirect911Conditions,
//     defaultOfficerIssueDescription: { id, code, d } }
// Only the DEFAULT officer-issue entry is kept — types with option-based
// variants (SAFETY_RISK/TIME) still resolve to DEFAULT when no selections
// are supplied by the caller. iconUrl is dropped (always null server-side).

const fs = require('node:fs');
const path = require('node:path');

const SRC = path.join(__dirname, '..', 'doc', 'wots_incident_types_raw.json');
const OUT = path.join(__dirname, '..', 'src', 'types.js');

const raw = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const regionId = raw.regionId;
const version = raw.version;

const types = {};
let count = 0;
for (const g of raw.groups) {
  const group = g.group;
  for (const t of g.types) {
    const oids = t.officerIssueDescriptions || [];
    const defaultOid = oids.find((o) => o.id === 'DEFAULT') || null;
    types[t.type] = {
      typeName: t.typeName,
      group,
      subgroup: t.subgroupName,
      snoozable: Boolean(t.snoozable),
      redirect911: Boolean(t.redirect911),
      redirect911Conditions: t.redirect911Conditions || [],
      defaultOfficerIssueDescription: defaultOid && { id: defaultOid.id, code: defaultOid.code, d: defaultOid.d },
    };
    count += 1;
  }
}

const header = `'use strict';

// Auto-generated by scripts/build-types.js from doc/wots_incident_types_raw.json.
// Do not edit by hand — rerun the script to regenerate.
// Source region: ${regionId}
// Source version: ${version}
// Total types: ${count}

`;

const body = 'const TYPES = ' + JSON.stringify(types, null, 2) + ';\n\n'
  + 'module.exports = { TYPES, REGION_ID: ' + JSON.stringify(regionId) + ' };\n';

fs.writeFileSync(OUT, header + body);
const bytes = fs.statSync(OUT).size;
console.log(`wrote ${OUT} — ${count} types, ${bytes} bytes`);
