'use strict';

// Auto-generated by scripts/build-types.js from doc/wots_incident_types_raw.json.
// Do not edit by hand — rerun the script to regenerate.
// Source region: us.nj.jersey_city
// Source version: 1522243945615458300
// Total types: 89

const TYPES = {
  "HIT_RUN_PERSON_STRUCK": {
    "typeName": "Hit and run",
    "group": "VEHICLE",
    "subgroup": "Accident: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D14.00",
      "d": "HIT AND RUN (PERSON STRUCK ); TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "LEAVING_SCENE_ACCIDENT_PROPERTY_ONLY": {
    "typeName": "Leaving the scene",
    "group": "VEHICLE",
    "subgroup": "Accident: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D15.00",
      "d": "LEAVING THE SCENE OF A ACCIDENT ( PROPERTY DAMAGE ONLY ); TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "PEDESTRIAN_STRUCK": {
    "typeName": "Pedestrian hit",
    "group": "VEHICLE",
    "subgroup": "Accident: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D13.00",
      "d": "PEDESTRIAN STRUCK; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "MOTOR_VEHICLE_ACCIDENT": {
    "typeName": "Vehicle accident",
    "group": "VEHICLE",
    "subgroup": "Accident: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D11.00",
      "d": "MOTOR VEHICLE ACCIDENT; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "CROSSWALK_PARKING_VIOLATION": {
    "typeName": "Parking in crosswalk",
    "group": "VEHICLE",
    "subgroup": "Parking: ",
    "snoozable": true,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D22.00",
      "d": "CROSSWALK PARKING VIOLATION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "DRIVEWAY_PARKING_VIOLATION": {
    "typeName": "Car blocking my driveway",
    "group": "VEHICLE",
    "subgroup": "Parking: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D23.00",
      "d": "DRIVEWAY PARKING VIOLATION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "HANDICAPPED_PARKING": {
    "typeName": "Illegal handicapped parking",
    "group": "VEHICLE",
    "subgroup": "Parking: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D34.00",
      "d": "HANDICAPPED PARKING; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "HYDRANT_PARKING_VIOLATION": {
    "typeName": "Blocked fire hydrant",
    "group": "VEHICLE",
    "subgroup": "Parking: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D21.00",
      "d": "HYDRANT PARKING VIOLATION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "OTHER_PARKING_VIOLATION": {
    "typeName": "Other illegal parking",
    "group": "VEHICLE",
    "subgroup": "Parking: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D24.00",
      "d": "OTHER PARKING VIOLATION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "NO_CITY_PERMIT_PARKING_VIOLATION": {
    "typeName": "Parking without valid permit",
    "group": "VEHICLE",
    "subgroup": "Parking: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D28.00",
      "d": "NO CITY PERMIT PARKING VIOLATION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ABANDONED_APPARENT_STOLEN": {
    "typeName": "Abandoned Vehicle",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D25.00",
      "d": "ABANDONED/APPARENT STOLEN; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "DISABLED_VEHICLE": {
    "typeName": "Disabled Vehicle",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D29.00",
      "d": "DISABLED VEHICLE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "INTOXICATED_DRIVER": {
    "typeName": "Drunk Driver",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D17.00",
      "d": "INTOXICATED DRIVER; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "SIGN_DOWN_TRAFFIC_LIGHT_OUT": {
    "typeName": "Missing sign or broken signal",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D16.00",
      "d": "SIGN DOWN/TRAFFIC LIGHT OUT OF ORDER; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ROADWAY_OBSTRUCTION": {
    "typeName": "Obstruction in roadway",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D26.00",
      "d": "ROADWAY OBSTRUCTION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "OTHER_VEHICLE_TRAFFIC_PROBLEM": {
    "typeName": "Other vehicle or traffic problems",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D31.00",
      "d": "OTHER VEHICLE/TRAFFIC PROBLEM; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "TRAFFIC_CONGESTION": {
    "typeName": "Traffic congestion",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D19.00",
      "d": "TRAFFIC CONGESTION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "MOTOR_VEHICLE_RUNNING_UNATTENDED": {
    "typeName": "Vehicle running, no driver",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D12.00",
      "d": "MOTOR VEHICLE RUNNING UNATTENDED; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "RACING_SPEEDING_CARELESS_DRIVING": {
    "typeName": "Wreckless driving",
    "group": "VEHICLE",
    "subgroup": "Traffic: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "D18.00",
      "d": "RACING/SPEEDING/CARELESS DRIVING; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "MERCHANT_CUSTOMER_DISPUTE": {
    "typeName": "Customer / merchant dispute",
    "group": "QOL",
    "subgroup": "Dispute: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B21.00",
      "d": "MERCHANT/CUSTOMER DISPUTE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "NEIGHBOR_DISPUTE": {
    "typeName": "Neighbors disbute",
    "group": "QOL",
    "subgroup": "Dispute: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B17.00",
      "d": "NEIGHBOR DISPUTE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "OTHER_INTER_CONFLICT": {
    "typeName": "Other conflict or dispute",
    "group": "QOL",
    "subgroup": "Dispute: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B23.00",
      "d": "OTHER INTER/CONFLICT; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "PUBLIC_ARGUMENT": {
    "typeName": "Public argument",
    "group": "QOL",
    "subgroup": "Dispute: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B19.00",
      "d": "PUBLIC ARGUMENT; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "TENANT_LANDLORD_DISPUTE": {
    "typeName": "Tenant & landlord dispute",
    "group": "QOL",
    "subgroup": "Dispute: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B18.00",
      "d": "TENANT/LANDLORD DISPUTE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "INTOXICATED_PERSON": {
    "typeName": "Drunk in public",
    "group": "QOL",
    "subgroup": "Illegal behavior: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E16.00",
      "d": "INTOXICATED PERSON; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "GAMBLING": {
    "typeName": "Gambling",
    "group": "QOL",
    "subgroup": "Illegal behavior: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G14.00",
      "d": "GAMBLING; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "LEWDNESS": {
    "typeName": "Lewdness",
    "group": "QOL",
    "subgroup": "Illegal behavior: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G11.00",
      "d": "LEWDNESS; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "PROSTITUTION": {
    "typeName": "Prostitution",
    "group": "QOL",
    "subgroup": "Illegal behavior: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G12.00",
      "d": "PROSTITUTION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "STREET_GAMES": {
    "typeName": "Street games",
    "group": "QOL",
    "subgroup": "Illegal behavior: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E18.00",
      "d": "STREET GAMES; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "LIQUOR_POSSESSION_BY_MINOR": {
    "typeName": "Underage drinking",
    "group": "QOL",
    "subgroup": "Illegal behavior: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G16.00",
      "d": "LIQUOR POSSESSION BY MINOR; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "FIREWORKS": {
    "typeName": "Fireworks",
    "group": "QOL",
    "subgroup": "Noise: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E17.00",
      "d": "FIREWORKS; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "LOUD_MUSIC": {
    "typeName": "Loud music",
    "group": "QOL",
    "subgroup": "Noise: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E13.00",
      "d": "LOUD MUSIC; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "NOISE": {
    "typeName": "Other loud noises",
    "group": "QOL",
    "subgroup": "Noise: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E12.00",
      "d": "NOISE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ANIMAL_COMPLAINT": {
    "typeName": "Animal complaint",
    "group": "QOL",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H22.00",
      "d": "ANIMAL COMPLAINT; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "HARASSMENT_VERBAL_ABUSE": {
    "typeName": "Harrassment",
    "group": "QOL",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B14.00",
      "d": "HARASSMENT(VERBAL ABUSE); TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "LOITERING": {
    "typeName": "Loitering",
    "group": "QOL",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E15.00",
      "d": "LOITERING; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "OTHER_PUBLIC_NUISANCE": {
    "typeName": "Public nuisance",
    "group": "QOL",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E21.00",
      "d": "OTHER PUBLIC NUISANCE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BURG_ALARM_COMMERCIAL_PROP": {
    "typeName": "Alarm (commercial)",
    "group": "SAFETY",
    "subgroup": "Commercial property: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C31.00",
      "d": "BURG ALARM COMMERCIAL PROP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BURGLARY_COMERCIAL_PROP": {
    "typeName": "Burglary (commercial)",
    "group": "SAFETY",
    "subgroup": "Commercial property: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C19.00",
      "d": "BURGLARY COMERCIAL PROP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "DAMAGE_COMMERICIAL": {
    "typeName": "Damage to commercial property",
    "group": "SAFETY",
    "subgroup": "Commercial property: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C13.00",
      "d": "DAMAGE COMMERICIAL; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ROB_COMMERCIAL": {
    "typeName": "Robbery (commercial)",
    "group": "SAFETY",
    "subgroup": "Commercial property: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A19.00",
      "d": "ROB COMERCIAL; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "SHOPLIFTING": {
    "typeName": "Shoplifting",
    "group": "SAFETY",
    "subgroup": "Commercial property: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C25.00",
      "d": "SHOPLIFTING; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ASSAULT_WEAPON": {
    "typeName": "Assault, weapon",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A11.00",
      "d": "ASSAULT WEAPON; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ASSAULT_NO_WEAPON": {
    "typeName": "Assualt, no weapon",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A12.00",
      "d": "ASSAULT NO WEAPON; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "FRAUD": {
    "typeName": "Fraud",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C36.00",
      "d": "FRAUD; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "HOMICIDE": {
    "typeName": "Homicide",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A24.00",
      "d": "HOMICIDE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "OTHER_PERSON_CRIME": {
    "typeName": "Other person crime ",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A31.00",
      "d": "OTHER PERSON CRIME; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "FIREARM_PERSON_WITH": {
    "typeName": "Person with weapon, firearm",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G18.00",
      "d": "FIREARM PERSON WITH; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "WEAPON_PERSON_WITH": {
    "typeName": "Person with weapon, other",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G19.00",
      "d": "WEAPON PERSON WITH; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ROB_PERSON": {
    "typeName": "Robbery",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A22.00",
      "d": "ROB PERSON; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "STREET_FIGHT_NO_WEAPONS": {
    "typeName": "Street fight",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E14.00",
      "d": "STREET FIGHT ( NO WEAPONS ); TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "THEFT_FROM_PERSON": {
    "typeName": "Theft",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A16.00",
      "d": "THEFT FROM PERSON; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "TERRORISTIC_THREATS": {
    "typeName": "Threats of violancce",
    "group": "SAFETY",
    "subgroup": "Crime against person: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B11.00",
      "d": "TERRORISTIC THREATS; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "INTERFERE_W_CUSTODY": {
    "typeName": "Custody",
    "group": "SAFETY",
    "subgroup": "Domestic issue: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "B12.00",
      "d": "INTERFERE W/ CUSTODY; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "USE_SALE_OF_DRUGS": {
    "typeName": "Drug use",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G13.00",
      "d": "USE/SALE OF DRUGS; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "EXPLOSIVE_DEVICE_FOUND": {
    "typeName": "Explosive device found",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "F17.00",
      "d": "EXPLOSIVE DEVICE FOUND; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "FIRE_EXPLOSION": {
    "typeName": "Fire or explostion",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H14.00",
      "d": "FIRE / EXPLOSION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ODOR_OF_GAS_TOXIC_SPILL": {
    "typeName": "Gas odor",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H17.00",
      "d": "ODOR OF GAS / TOXIC SPILL; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "UTILITY_BREAK_INTERRUPTION": {
    "typeName": "Gas or electric outage",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H21.00",
      "d": "UTILITY BREAK / INTERRUPTION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "INDUSTRIAL_CONSTRUCTION_MISHAP": {
    "typeName": "Industrial or construction safety issue",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H34.00",
      "d": "INDUSTRIAL / CONSTRUCTION MISHAP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "STRANGE_ODOR": {
    "typeName": "Strange odor",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "E19.00",
      "d": "STRANGE ODOR; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ELEVATOR_STUCK_W_OCCUPANTS": {
    "typeName": "Stuck elevator",
    "group": "SAFETY",
    "subgroup": "General safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H33.00",
      "d": "ELEVATOR STUCK W/OCCUPANTS; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BOMB_THREAT": {
    "typeName": "Bomb threat",
    "group": "SAFETY",
    "subgroup": "General safty: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "F15.00",
      "d": "BOMB THREAT; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BURG_ALARM_RESIDENTIAL_PROP": {
    "typeName": "Alarm (residential)",
    "group": "SAFETY",
    "subgroup": "Home: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C29.00",
      "d": "BURG ALARM RESIDENTIAL PROP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BURGLARY_RESIDENTIAL_PROP": {
    "typeName": "Burglary (residential)",
    "group": "SAFETY",
    "subgroup": "Home: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C18.00",
      "d": "BURGLARY RESIDENTIAL PROP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "DAMAGE_RESIDENTIAL": {
    "typeName": "Damage (residential)",
    "group": "SAFETY",
    "subgroup": "Home: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C12.00",
      "d": "DAMAGE RESIDENTIAL; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "ROB_AT_RESIDENCE": {
    "typeName": "Robbery (residential)",
    "group": "SAFETY",
    "subgroup": "Home: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A18.00",
      "d": "ROB AT RESIDENCE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "TRESPASS": {
    "typeName": "Tresspassing (residential)",
    "group": "SAFETY",
    "subgroup": "Home: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C16.00",
      "d": "TRESPASS; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "MISSING_PERSON": {
    "typeName": "Missing person",
    "group": "SAFETY",
    "subgroup": "Individual safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "A26.00",
      "d": "MISSING PERSON; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "AMBULANCE_REQUEST_FOR": {
    "typeName": "Request for ambulance",
    "group": "SAFETY",
    "subgroup": "Individual safety: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H13.00",
      "d": "AMBULANCE REQUEST FOR; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "OTHER_ASSISTANCE": {
    "typeName": "Request for assistance",
    "group": "SAFETY",
    "subgroup": "Individual safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H35.00",
      "d": "OTHER ASSISTANCE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "CHECK_WELFARE_OF": {
    "typeName": "Safety check, personal welfare",
    "group": "SAFETY",
    "subgroup": "Individual safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H32.00",
      "d": "CHECK WELFARE OF; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "SUSPICIOUS_PERSON_CONDITION": {
    "typeName": "Suspicious person",
    "group": "SAFETY",
    "subgroup": "Individual safety: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "INJURY",
      "INJURY_INTENDED",
      "NOW;INJURY",
      "HAPPENED;INJURY",
      "NOW;INJURY_INTENDED",
      "HAPPENED;INJURY_INTENDED",
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "F16.00",
      "d": "SUSPICIOUS PERSON/CONDITION; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BURG_ALARM_MOTOR_VEHICLE": {
    "typeName": "Alarm (vehicle)",
    "group": "SAFETY",
    "subgroup": "Motor vehicle: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C32.00",
      "d": "BURG ALARM MOTOR VEHICLE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "DAMAGE_MOTOR_VEHICLE": {
    "typeName": "Damage to vehicle",
    "group": "SAFETY",
    "subgroup": "Motor vehicle: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C14.00",
      "d": "DAMAGE MOTOR VEHICLE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "THEFT_PROP_FROM_VEHICLE": {
    "typeName": "Theft of property in vehicle",
    "group": "SAFETY",
    "subgroup": "Motor vehicle: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C22.00",
      "d": "THEFT PROP FROM VEHICLE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "MOTOR_VEHICLE_THEFT": {
    "typeName": "Theft of vehicle",
    "group": "SAFETY",
    "subgroup": "Motor vehicle: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C27.00",
      "d": "MOTOR VEHICLE THEFT; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BURG_ALARM_OTHER": {
    "typeName": "Alarm",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C33.00",
      "d": "BURG ALARM OTHER; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "BURGLARY_OTHER_STRUCTURE_AREA": {
    "typeName": "Burglary",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C21.00",
      "d": "BURGLARY OTHER STRUCTURE/AREA; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "DAMAGE_OTHER_PROP": {
    "typeName": "Damage to property",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C15.00",
      "d": "DAMAGE OTHER PROP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "DEAD_BODY": {
    "typeName": "Dead body",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H29.00",
      "d": "DEAD BODY; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "FOUND_PARAPHERNALIA": {
    "typeName": "Drug paraphernalia found",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G23.00",
      "d": "FOUND CDS/PARAPHERNALIA; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "LOST_MISLAID_PROPERTY": {
    "typeName": "Lost property",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H23.00",
      "d": "LOST / MISLAID PROPERTY; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "PERSON_DOWN_CAUSE_UNKNOWN": {
    "typeName": "Person down or injured",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": true,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "H31.00",
      "d": "PERSON DOWN/CAUSE UNKNOWN; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "POSSESSION_STOLEN_PROP": {
    "typeName": "Posession of stolen property",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C26.00",
      "d": "POSSESSION STOLEN PROP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "OTHER_PROP_CRIME": {
    "typeName": "Property crime",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C35.00",
      "d": "OTHER PROP CRIME; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "THEFT_OTHER_PROP": {
    "typeName": "Theft of property",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C24.00",
      "d": "THEFT OTHER PROP; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "THEFT_OF_SERVICE": {
    "typeName": "Theft of service",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [
      "NOW",
      "NOW;NO_INJURY"
    ],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "C23.00",
      "d": "THEFT OF SERVICE; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  },
  "FOUND_WEAPON": {
    "typeName": "Weapon found",
    "group": "SAFETY",
    "subgroup": "Other: ",
    "snoozable": false,
    "redirect911": false,
    "redirect911Conditions": [],
    "defaultOfficerIssueDescription": {
      "id": "DEFAULT",
      "code": "G22.00",
      "d": "FOUND WEAPON; TIME ELAPSED NOT APPLICABLE; INJURY NOT APPLICABLE"
    }
  }
};

module.exports = { TYPES, REGION_ID: "us.nj.jersey_city" };
